<?php
if (!empty($block->getSubscriptionCardData())) {
    ?>
    <section class="admin__page-section order-view-billing-shipping">
        <div class="admin__page-section-title">
            <span class="title"><?php echo $block->escapeHtml(__('Nets Subscription Details')); ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-payment-method">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo $block->escapeHtml(__('Card Information')); ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <div class="order-payment-method-title">
                        <table class="data-table admin__table-secondary">
                            <tbody>
                                <tr>
                                    <th><?php echo $block->escapeHtml(__('Card Number')); ?> :</th>
                                    <td><?php echo $block->escapeHtml(json_decode($block->getSubscriptionCardData())->masked_pan); ?></td>
                                </tr>
                                <tr>
                                    <th><?php echo $block->escapeHtml(__('Expiry Date')); ?> :</th>
                                    <td><?php echo $block->escapeHtml(json_decode($block->getSubscriptionCardData())->expiry_date); ?></td>
                                </tr>
                                <tr>
                                    <th><?php echo $block->escapeHtml(__('Payment Type')); ?> :</th>
                                    <td><?php echo $block->escapeHtml(json_decode($block->getSubscriptionCardData())->payment_type); ?></td>
                                </tr>
                                <tr>
                                    <th><?php echo $block->escapeHtml(__('Payment Method')); ?> :</th>
                                    <td><?php echo $block->escapeHtml(json_decode($block->getSubscriptionCardData())->payment_method); ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="order-payment-additional">
                    </div>
                </div>
            </div>

            <div class="admin__page-section-item order-shipping-method">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo $block->escapeHtml(__('Subscription Information')); ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <div class="order-payment-method-title">
                        <table class="data-table admin__table-secondary">
                            <tbody>
                                <tr>
                                    <th><?php echo $block->escapeHtml(__('Nets Subscription Id')); ?> :</th>
                                    <td><?php echo $block->escapeHtml(json_decode($block->getSubscriptionCardData())->nets_subscription_id); ?></td>
                                </tr>
                                <tr>
                                    <th><?php echo $block->escapeHtml(__('Nets Subscription End Date')); ?> :</th>
                                    <td><?php echo $block->escapeHtml(json_decode($block->getSubscriptionCardData())->nets_subscription_enddate); ?></td>
                                </tr>
                            </tbody>
                        </table>
                        <?php
                 $subDetails =$block->getSubscriptionCardDetails();

                 
                 ?>
                 </br>
                   <div class="admin__field">
                <div class="admin__page-section-item-title">
                    <div class="tooltip">
                      <span class="tooltiptext">If subscription status is Inactive subscription charge will be pause and 
                        if status is Cancel then subscription will be closed.</span>
                        <div class="admin__page-section-item-title">
                          <span class="title"><?php echo $block->escapeHtml(__('Subscription Status')); ?></span><label style="font-size: 22px">&#x1F6C8; </label>
                       </div>
                    </div>
                    <?php if($subDetails[0]['status']=='2'){?>
                    <label style="color: red;"><b>Subscription has been closed.</b></label>
                    <?php }?>
                </div>
                     
                    <!-- <label for="history_status"  class="admin__field-label">Subscription Status</label> -->
                    <input type="hidden" id="subid" name="SubID" value="<?php echo $subDetails[0]['nets_subscription_id'];?>" />
                    <input type="hidden" id="subStatus" name="subStatus" value="<?php echo $subDetails[0]['status'];?>" />
                    <input type="hidden" id="orderID" name="orderID" value="<?php echo $subDetails[0]['order_id'];?>" />
                    
                    <div class="admin__field-control">
                        <select name="subscription[status]" id="subscription_status" class="admin__control-select" <?=($subDetails[0]['status']=='2')?'disabled':'';?>  >
                                <option value="1" <?=($subDetails[0]['status']=='1')?'selected':'';?> > Active  </option>
                                <option value="0" <?=($subDetails[0]['status']=='0')?'selected':'';?> > Inactive </option>
                                <option value="2" <?=($subDetails[0]['status']=='2')?'selected':'';?> > Cancel   </option>
                        </select>
                    </div>
                    
                   
                    </div>                     
                </div>
            </div>
        </div>
    </section>
    <!-- <section class="admin__page-section-history"> -->
<div class="admin__page-section-item">
    
    <div class="admin__table-wrapper">
    <div class="admin__page-section-title">
        <span class="title">Subscription History</span>
    </div>
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
                <tr class="headings">
                            <th class="col-product"><span>Sr. No.</span></th>
                            <!--th class="col-status"><span>Order ID</span></th-->
                            <th class="col-price-original"><span>Nets Payment ID</span></th>
                            <th class="col-price"><span>Charge Order ID</span></th>
                            <th class="col-ordered-qty"><span>Status</span></th>
                            <th class="col-subtotal"><span>Initiate Date</span></th>
                            <th class="col-subtotal"><span>Charge Date</span></th>
                            <th class="col-action"><span>Action</span></th>
                    </tr>
            </thead>
            <tbody class="even">
                <?php 
                if(!empty($block->getSubscriptionInterval())) {
                 $i=1;
                foreach ($block->getSubscriptionInterval() as $rows) {?>
                <tr>
                    <td class="col-product">
                        <div id="order_item_753">
                            <div id="order_item_753_title" class="product-title"><?php echo $i; ?> </div>
                        </div>        
                    </td>
                    <!--td class="col-status"><?php //echo $rows['OrderID']; ?> </td-->
                    <td class="col-price-original"><span class="price"></span><?php echo $rows['PaymentID']; ?> </td>
                    <td class="col-price"><div class="price-incl-tax"><?php echo $rows['ChildOrderId']; ?></div></td>
                    <td class="col-ordered-qty"><?php echo $rows['SubStatus']; ?></td>
                    <td class="col-subtotal"><?php echo $rows['created_at']; ?></td>
                    <td class="col-subtotal"><?php echo $rows['updated_at']; ?></td>
                    <td class="col-status">
                        <?php if($rows['SubStatus'] == "Failed") { ?>
                            <button id="subscription_charge" title="Charge" type="button" class="subscription_charge action-default scalable charge primary" backend-button-widget-hook-id="buttonId8n6HS1qWAp" data-ui-id="">
                                <span>Charge</span>
                            </button>
                            <input type="hidden" id="bulkID" name="bulkID" value="<?php echo $rows['BulkId'];?>" />
                    
                        <?php } ?>
                        <?php if($rows['SubStatus'] == "Succeeded" || $rows['SubStatus'] == "Manualy_Charged" ) { ?>
                            <select name="subscription-refund" id="subscription-refund" class="subscription-refund">
                              <option value="0">Select Refund Option</option>
                              <option value="refund-specific[<?php echo $rows['PaymentID']; ?>]">Refund</option>
                              <option value="refund-partial-specific[<?php echo $rows['PaymentID']; ?>]">Partial Refund</option>
                            </select>
                        <?php } ?>
                        <?php if($rows['SubStatus'] == "Partially Refunded") { ?>
                            <select name="subscription-refund" id="subscription-refund" class="subscription-refund">
                              <option value="0">Select Refund Option</option>
                              <option value="refund-partial-specific[<?php echo $rows['PaymentID']; ?>]">Partial Refund</option>
                            </select>
                        <?php } ?>
                    </td>
                </tr> 
              <?php $i++; } 
              } else { ?>   
                <tr>
                <td class="col" colspan="7" style="text-align: center;"><strong>No Records Available</strong></td>
                </tr>
              <?php } ?>      
                </tbody>
        </table>
    </div>
</div>
<div id="popup-modal" style="display:none;">
    <h1> Hi I m here.... </h1>
</div>
<?php } ?>

<script type="text/javascript">
require(
  [
    "jquery",
    'mage/url',
    'Magento_Ui/js/modal/modal'
  ],
  function($,mageurl,modal) {
    
    var options = {
      type: 'popup',
      responsive: true,
      innerScroll: true,
      title: 'Partial Refund',
      id : 'title_page',
      buttons: [{
          text: $.mage.__('Close'),
          class: '',
          click: function () {
              this.closeModal();
          },
          text: $.mage.__('Partial Refund'),
          class: 'refund-partial-button',
          click: function () {
          var refundOption = '';
          var isSelected = false;
          if($('#r-shipping').is(':checked')) {
             refundOption = 'shipping';
             isSelected = true;
          }
          if($('#r-product').is(':checked')) {
             refundOption = 'product';
             isSelected = true;
          }
          
          if(!isSelected){
            alert('Please select an item to refund.');
            return;
          }
          var id = $("#oid").val();
          var paymentid = $("#pid").val();
          var productTotal = $("#refund_ptotal").val();
          var shippingTotal = $("#refund_total").val();
              refundPartial(id, paymentid, productTotal, shippingTotal, refundOption);
          }
      }]
  };



    $("#subscription_status").on('change', function(){
        console.log("list item selected");
        var val = $(this).val();   
        
        var subID = $("#subid").val();
        var orderID = $("#orderID").val();
        var subStatus = $("#subscription_status").val();
        // console.log(subID);

        $(document).ready(function() {
            var customurl = "https://mg2yk.sokoni.it/easycheckout/order/SubscriptionUpdate/";
                $.ajax({
                    url: "<?php  echo $block->getUrl('grid/subscription'); ?>",
                    type: 'POST',
                    dataType: 'json',
                    data: {
                            subscription_id: subID,
                            subscription_status:subStatus ,
                            id: orderID,
                        },
                complete: function(response)
                {             
                    var responseData = response.responseJSON;
                    if(responseData.status == '2') {
                        console.log(responseData);
                           location.reload();
                    }
                
                },
                    // error: function (xhr, status, errorThrown)
                    //  {
                    //     console.log('Error happens. Try again.');
                    // }
                });
        });
    });
    
    $('.subscription-refund').change(function(){
      const arrRefund = $(this).val().split("[");
      if("refund-specific" == arrRefund[0]){
        $(document).ready(function() {
        const paymentId = arrRefund[1].split("]");
        const refundType = 'full';
        var orderID = $("#orderID").val();
            $.ajax({
                url: "<?php  echo $block->getUrl('grid/subscription/Refund'); ?>",
                type: 'POST',
                dataType: 'json',
                data: {
                    payment_id: paymentId[0],
                    id: orderID,
                    type: refundType
                },
                complete: function(response)
                {      
                  var responseData = response.responseJSON;
                  if(responseData.status == 'Success') {
                    location.reload();
                  }
                },
                error: function (xhr, status, errorThrown)
                  {  
                      alert('Refund amount must be less or equal to charged amount');
                 }
            });
        });
      } else{
        var orderID = $("#orderID").val();
        const arrRefund = $(this).val().split("[");
        const paymentId = arrRefund[1].split("]");
        $.ajax({
            url: "<?php  echo $block->getUrl('grid/subscription/SubscriptionOrderItems'); ?>",
            type: 'POST',
            dataType: 'json',
            data: {
                payment_id: paymentId[0],
                id: orderID
            },
            complete: function(response)
            {      
              var responseData = response.responseJSON;
              if(responseData.status == 'Success') {
                console.log(responseData.row);
                console.log(responseData.row['orderItem']['name']);
                console.log(responseData.row.orderItem.name);
                var partialData= '<input type="hidden" name="partial-id" id="oid" value="'+orderID+'"/>';
                partialData+= '<input type="hidden" name="payment-id" id="pid" value="'+paymentId[0]+'"/>';
                if (typeof responseData.row.shipping !== 'undefined') {
                  var shipping = '<tr>';
                    shipping += '<td><input type="radio" id="r-shipping" name="refund-items" value="Shipping"></td>';
                    shipping += '<td><b>Shipping</b></td>';
                    shipping += '<td>'+responseData.row.shipping.name+'</td>';
                    shipping += '<td>1</td>';
                    shipping += '<td><input type="text" id="refund_total" name="total" value="'+responseData.row.shipping.total/100+'" />'+'</td>';
                  shipping += '</tr>';
                }
                var row = '<div id="refund-items">';
                row += '<input type="hidden" name="partial-id" id="oid" value="'+orderID+'"/>';
                row += '<input type="hidden" name="payment-id" id="pid" value="'+paymentId[0]+'"/>';
                row += '<style> table { border-collapse: collapse; width: 100%;}th, td {padding: 8px; text-align: left; border-bottom: 1px solid #DDD;}';
                row += 'tr:hover {background-color: #D6EEEE;}</style>';
                row += '<table>';
                  row += '<tr>';
                    row += '<th>Refund Options</th>';
                    row += '<th>Cart Items</th>';
                    row += '<th>Name</th>';
                    row += '<th>Qty</th>';
                    row += '<th>Total</th>';
                  row += '</tr>';
                  row += '<tr>';
                    row += '<td><input type="radio" id="r-product" name="refund-items" value="product"></td>';
                    row += '<td><b>'+responseData.row.orderItem.type+'</b></td>';
                    row += '<td>'+responseData.row.orderItem.name+'</td>';
                    row += '<td>'+responseData.row.orderItem.qty+'</td>';
                    row += '<td><input type="text" id="refund_ptotal" name="qty" value="'+responseData.row.orderItem.total/100+'" />'+'</td>';
                    
                  row += '</tr>';
                  row += shipping;

                  //row += '<tr>';
                   // row += '<td>Centro comercial Moctezuma</td>';
                   // row += '<td>Francisco Chang</td>';
                   // row += '<td>Mexico</td>';
                  //row += '</tr>';
                row += '</table>';
                row += '</div>';
                //row += '<div><input type="button" value="Refund Partial" onclick="test('+responseData.row.shipping.total+', '+responseData.row.orderItem.qty+', '+orderID+', '+ "'"+paymentId[0]+"'" +')"/></div>';
                var popup = modal(options, $('#popup-modal'));
                $("#popup-modal").modal("openModal");
                $('#popup-modal').html(row);
                //$('#popup-modal').html(partialData);
              }
            },
            error: function (xhr, status, errorThrown)
              {
                 console.log('Something went wrong. Try again.');
             }
        });
        
      }
    });
    
    function refundPartial(id, pid, pTotal, sTotal, refundOption){
  const refundType = 'partial';
  $.ajax({
    url: "<?php  echo $block->getUrl('grid/subscription/Refund'); ?>",
    type: 'POST',
    dataType: 'json',
    data: {
        payment_id: pid,
        id: id,
        productTotal: pTotal,
        total: sTotal,
        type: refundType,
        option: refundOption
    },
    complete: function(response)
    {      
      var responseData = response.responseJSON;
      if(responseData.status == 'Success') {
        location.reload();
      }
    },
    error: function (xhr, status, errorThrown)
      {  
          alert('Refund amount must be less or equal to charged amount');
     }
  });
};

    $(".subscription_charge").on('click', function(){
        // console.log("list item selected");
        var currentRow=$(this).closest("tr"); 
         
        // var subID = currentRow.find("td:eq(3)").text();
        var subID = $("#subid").val();
        var bulkID = $("#bulkID").val();
        
        // alert(bulkID);
        
        $(document).ready(function() {
            $.ajax({
                url: "<?php  echo $block->getUrl('grid/subscription/Charge'); ?>",
                type: 'POST',
                dataType: 'json',
                data: {
                    subscription_id: subID,
                    bulk_id: bulkID
                },
                complete: function(response)
                {      
                       
              var responseData = response.responseJSON;
              if(responseData.status == 'Success') {
                location.reload();
              }
            },
                error: function (xhr, status, errorThrown)
                  {
                     console.log('Error happens. Try again.');
                 }
            });
        });
    });
});

</script>
<style>
.tooltip {
  position: relative;
  display: inline-block;
   /* border-bottom: 1px dotted black; */ */
}

.tooltip .tooltiptext {
  visibility: hidden;
  width: 400px;
  background-color: #847c7c;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 10px 20px;

  /* Position the tooltip */
  position: absolute;
  z-index: 1;
  top: -63px;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
}
</style>